name: Auto Delete File

on:
  schedule:
    # 每分钟执行一次
    # 请注意：GitHub Actions 的 schedule 事件不是精确的，可能会有几分钟的延迟。
    # 更多关于 cron 表达式的信息：https://crontab.guru/
    - cron: '*/1 * * * *'
  workflow_dispatch:
    # 允许手动触发此 workflow，方便测试

jobs:
  delete_file_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # 使用最新的 Python 3 版本

    - name: Install dependencies
      run: pip install requests

    - name: Run delete script
      env:
        # GITHUB_TOKEN 是 GitHub Actions 内置的 token，具有当前仓库的读写权限。
        # 你也可以在这里使用你自己的 Personal Access Token，但内置 token 更安全方便。
        # 如果你想删除私有仓库的文件，或者执行更高级的操作，可能需要使用 Personal Access Token
        # 但对于当前需求，默认的 GITHUB_TOKEN 应该足够。
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # GITHUB_REPOSITORY 是 GitHub Actions 内置的环境变量，格式为 "owner/repo"
        GITHUB_REPOSITORY: ${{ github.repository }}
        # 这是你想要删除的文件路径
        FILE_PATH_TO_DELETE: 'Notes/transfer.txt' # <-- 将这里替换为你要删除的实际文件路径
      run: python delete_file.py

