name: Auto Delete File from Queue

on:
  schedule:
    # 每分钟执行一次
    # 请注意：GitHub Actions 的 schedule 事件不是精确的，可能会有几分钟的延迟。
    # 更多关于 cron 表达式的信息：https://crontab.guru/
    - cron: '*/1 * * * *'
  workflow_dispatch:
    # 允许手动触发此 workflow，方便测试

jobs:
  delete_file_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x' # 使用最新的 Python 3 版本

    - name: Install dependencies
      run: pip install requests

    - name: Run delete script
      env:
        # GITHUB_TOKEN 是 GitHub Actions 内置的 token，具有当前仓库的读写权限。
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # GITHUB_REPOSITORY 是 GitHub Actions 内置的环境变量，格式为 "owner/repo"
        GITHUB_REPOSITORY: ${{ github.repository }}
        # FILE_PATH_TO_DELETE 这个环境变量不再需要，因为 Python 脚本会从 delete_queue.json 中读取路径
      run: python delete_file.py

