name: Check and Delete Expired Files

on:
  schedule:
    - cron: '*/1 * * * *'  # 每分钟执行一次
  workflow_dispatch:      # 可手动触发

jobs:
  delete_expired:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # 避免使用默认 token

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install axios

      - name: Run deletion script
        run: node .github/scripts/delete_expired.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPO: moodHappy/HelloWorld