name: delete expired

on:
  schedule:
    - cron: '* * * * *'  # 每分钟执行一次
  workflow_dispatch:

jobs:
  delete_old_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Delete expired files
        run: |
          node .github/scripts/delete_expired.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add Notes/
          git commit -m "⏰ Auto delete expired files" || echo "No changes"
          git push
