name: delete expired

on:
  schedule:
    - cron: '*/20 * * * *'  # 每20分钟执行一次
  workflow_dispatch:

jobs:
  delete_old_files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Delete expired files
        run: |
          node .github/scripts/delete_expired.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add Notes/
          git commit -m "⏰ Auto delete expired files" || echo "No changes"
          # 在推送前，先尝试拉取远程最新更改并合并
          # 这能解决“远程仓库有新内容而本地没有”导致的推送失败问题
          git pull origin master --rebase || git pull origin master
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 确保git push也有权限
